In [27]:
import numpy as np
import pandas as pd
%pip install scikit-learn
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

def center_matrix(matrix):
    # Convert the input to a NumPy array
    matrix = np.array(matrix)
    
    # Calculate the mean of each column
    mean_x = np.mean(matrix[:, 0])
    mean_y = np.mean(matrix[:, 1])
    
    # Subtract the mean from each column
    centered_matrix = matrix - np.array([mean_x, mean_y])
    
    return centered_matrix

#Step 2B: You can also Standardize the data
def standardize_matrix(matrix):
    # Convert the input to a NumPy array
    matrix = np.array(matrix)
    
    # Calculate the mean and standard deviation of each column
    mean = np.mean(matrix, axis=0)
    std_dev = np.std(matrix, axis=0)
    
    # Standardize the data
    standardized_data = (matrix - mean) / std_dev
    
    return standardized_matrix


# Step 1: Create the dataset
matrix = [
    [1,2],
    [2,4],
    [3,6],
    [7,8]
]

# Step 2: Center the data
centered_matrix = center_matrix(matrix)


# Another approach Step 2: Standardize the data
#scaler = StandardScaler()
#standardized_data = scaler.fit_transform(df)

# Step 3: Calculate the covariance matrix
cov_matrix = np.cov(centered_matrix.T)

# Step 4: Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

# Step 5: Sort eigenvalues and eigenvectors
sorted_index = np.argsort(eigenvalues)[::-1]
sorted_eigenvalues = eigenvalues[sorted_index]
sorted_eigenvectors = eigenvectors[:, sorted_index]

# Step 6: Transform the data
transformed_data = np.dot(standardized_data, sorted_eigenvectors)

# Print results
print("Original Data:\n", np.array(matrix))
print("Centered Matrix:\n", centered_matrix)
print("Covariance Matrix:\n", cov_matrix)
print("Eigenvalues:\n", sorted_eigenvalues)
print("Eigenvectors:\n", sorted_eigenvectors)
print("Transformed Data:\n", transformed_data)


Note: you may need to restart the kernel to use updated packages.
Original Data:
 [[1 2]
 [2 4]
 [3 6]
 [7 8]]
Centered Matrix:
 [[-2.25 -3.  ]
 [-1.25 -1.  ]
 [-0.25  1.  ]
 [ 3.75  3.  ]]
Covariance Matrix:
 [[6.91666667 6.33333333]
 [6.33333333 6.66666667]]
Eigenvalues:
 [13.12623343  0.4570999 ]
Eigenvectors:
 [[ 0.71404937 -0.70009535]
 [ 0.70009535  0.71404937]]
Transformed Data:
 [[-1.64467038 -0.26638872]
 [-0.70497766  0.06489466]
 [ 0.23471506  0.39617803]
 [ 2.11493298 -0.19468397]]
