In [4]:
import numpy as np
import pandas as pd
%pip install scikit-learn
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# Step 1: Create the dataset
data = np.array([[1, 2], [2, 4], [3, 6], [7, 8]])
df = pd.DataFrame(data, columns=['x', 'y'])

# Step 2: Standardize the data
scaler = StandardScaler()
standardized_data = scaler.fit_transform(df)


# Step 3: Calculate the covariance matrix
cov_matrix = np.cov(standardized_data.T)

# Step 4: Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

# Step 5: Sort eigenvalues and eigenvectors
sorted_index = np.argsort(eigenvalues)[::-1]
sorted_eigenvalues = eigenvalues[sorted_index]
sorted_eigenvectors = eigenvectors[:, sorted_index]

# Step 6: Transform the data
transformed_data = np.dot(standardized_data, sorted_eigenvectors)

# Print results
print("Original Data:\n", df)
print("\nStandardized Data:\n", standardized_data)
print("\nCovariance Matrix:\n", cov_matrix)
print("\nEigenvalues:\n", sorted_eigenvalues)
print("\nEigenvectors:\n", sorted_eigenvectors)
print("\nTransformed Data:\n", transformed_data)


Note: you may need to restart the kernel to use updated packages.
Original Data:
    x  y
0  1  2
1  2  4
2  3  6
3  7  8

Standardized Data:
 [[-0.98787834 -1.34164079]
 [-0.5488213  -0.4472136 ]
 [-0.10976426  0.4472136 ]
 [ 1.6464639   1.34164079]]

Covariance Matrix:
 [[1.33333333 1.24356442]
 [1.24356442 1.33333333]]

Eigenvalues:
 [2.57689776 0.08976891]

Eigenvectors:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Transformed Data:
 [[ 1.64721877 -0.25014782]
 [ 0.70430303  0.0718475 ]
 [-0.23861271  0.39384282]
 [-2.11290909 -0.21554249]]
